# Generated by Django 4.0.7 on 2023-08-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('typeName', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Auncle', 'Auncle'), ('Aunt', 'Aunt'), ('GrandMa', 'GrandMa'), ('GrandPa', 'GrandPa')], max_length=50)),
                ('class_room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class_room')),
                ('family_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.family')),
            ],
        ),
    ]
